addSbtPlugin("org.typelevel" % "sbt-typelevel-ci-release" % "0.7.7")
addSbtPlugin("org.typelevel" % "sbt-typelevel-mergify" % "0.7.7")
addSbtPlugin("org.typelevel" % "sbt-typelevel-settings" % "0.7.7")
addSbtPlugin("com.github.cb372" % "sbt-explicit-dependencies" % "0.3.1")
addSbtPlugin("ch.epfl.scala" % "sbt-scalafix" % "0.14.3")
addSbtPlugin("com.eed3si9n" % "sbt-projectmatrix" % "0.11.0")
